
name: Java CI

on:
  push:
    branches:
     - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup Java JDK 8
      uses: actions/setup-java@v3.6.0
      with:
        distribution: temurin
        java-version: '8'
    - name: Download BuildTools
      run: wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        distribution: temurin
        java-version: 17
    - name: Build MC 1.18.2
      run: java -jar BuildTools.jar --rev 1.18.2 --remapped
    - name: Build MC 1.19.2
      run: java -jar BuildTools.jar --rev 1.19.2 --remapped
    - name: Build with Gradle
      run: ./gradlew obfuscate
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: UltraCosmetics-dev
        path: build/libs/UltraCosmetics-*.jar
